In [4]:
from src.cloud_storage.aws_storage import SimpleStorageService
from src.entity.artifact_entity import *
from src.entity.config_entity import *
from src.constants import *
from dotenv import load_dotenv
load_dotenv()
from src.pipline.training_pipeline import *
pipline = TrainPipeline()

ImportError: cannot import name '_is_pandas_df' from 'sklearn.utils.validation' (c:\Users\Anindya.Sarkar\Documents\Vehilce-insurance\.venv\Lib\site-packages\sklearn\utils\validation.py)

In [15]:
data_ingestion_artifact= pipline.start_data_ingestion()

[ 2026-01-18 10:22:49,749 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2026-01-18 10:22:49,750 ] root - INFO - Getting the data from mongodb
[ 2026-01-18 10:22:49,751 ] root - INFO - Entered initiate_data_ingestion method of Data_Ingestion class
[ 2026-01-18 10:22:49,752 ] root - INFO - Exporting data from mongodb
[ 2026-01-18 10:22:49,752 ] root - INFO - MongoDB connection successful.

Fetching data from mongoDB
Data fecthed with len: 762218

[ 2026-01-18 10:23:29,381 ] root - INFO - Shape of dataframe: (762218, 12)
[ 2026-01-18 10:23:29,383 ] root - INFO - Saving exported data into feature store file path: artifact\01_18_2026_10_09_58\data_ingestion\feature_store\data.csv
[ 2026-01-18 10:23:33,123 ] root - INFO - Got the data from mongodb
[ 2026-01-18 10:23:33,125 ] root - INFO - Entered split_data_as_train_test method of Data_Ingestion class
[ 2026-01-18 10:23:33,417 ] root - INFO - Performed train test split on the dataframe
[ 2026-01-18 10:23:33,419 ] root - INFO - Exited split_data_as_train_test method of Data_Ingestion class
[ 2026-01-18 10:23:33,420 ] root - INFO - Exporting train and test file path.
[ 2026-01-18 10:23:38,403 ] root - INFO - Exported train and test file path.
[ 2026-01-18 10:23:38,516 ] root - INFO - Performed train test split on the dataset
[ 2026-01-18 10:23:38,517 ] root - INFO - Exited initiate_data_ingestion method of Data_Ingestion class
[ 2026-01-18 10:23:38,517 ] root - INFO - Data ingestion artifact: DataIngestionArtifact(trained_file_path='artifact\\01_18_2026_10_09_58\\data_ingestion\\ingested\\train.csv', test_file_path='artifact\\01_18_2026_10_09_58\\data_ingestion\\ingested\\test.csv')
[ 2026-01-18 10:23:38,822 ] root - INFO - Got the train_set and test_set from mongodb
[ 2026-01-18 10:23:38,823 ] root - INFO - Exited the start_data_ingestion method of TrainPipeline class

In [16]:
data_validation_artifact = pipline.start_data_validation(data_ingestion_artifact=data_ingestion_artifact)

[ 2026-01-18 10:24:29,509 ] root - INFO - Entered the start_data_validation method of TrainPipeline class
[ 2026-01-18 10:24:29,533 ] root - INFO - Starting data validation
[ 2026-01-18 10:24:30,575 ] root - INFO - Is required column present: [True]
[ 2026-01-18 10:24:30,577 ] root - INFO - All required columns present in training dataframe: True
[ 2026-01-18 10:24:30,577 ] root - INFO - Is required column present: [True]
[ 2026-01-18 10:24:30,578 ] root - INFO - All required columns present in testing dataframe: True
[ 2026-01-18 10:24:30,579 ] root - INFO - All categorical/int columns present in training dataframe: True
[ 2026-01-18 10:24:30,579 ] root - INFO - All categorical/int columns present in testing dataframe: True
[ 2026-01-18 10:24:30,582 ] root - INFO - Data validation artifact created and saved to JSON file.
[ 2026-01-18 10:24:30,584 ] root - INFO - Data validation artifact: DataValidationArtifact(validation_status=True, message='', validation_report_file_path='artifact\\01_18_2026_10_09_58\\data_validation\\report.yaml')
[ 2026-01-18 10:24:30,606 ] root - INFO - Performed the data validation operation
[ 2026-01-18 10:24:30,607 ] root - INFO - Exited the start_data_validation method of TrainPipeline class

In [17]:
data_transformation_artifact = pipline.start_data_transformation(
                data_ingestion_artifact=data_ingestion_artifact, data_validation_artifact=data_validation_artifact)

[ 2026-01-18 10:24:35,342 ] root - INFO - Data Transformation Started !!!
[ 2026-01-18 10:24:36,422 ] root - INFO - Train-Test data loaded
[ 2026-01-18 10:24:36,469 ] root - INFO - Input and Target cols defined for both train and test df.
[ 2026-01-18 10:24:36,470 ] root - INFO - Mapping 'Gender' column to binary values
[ 2026-01-18 10:24:36,497 ] root - INFO - Dropping 'id' column
[ 2026-01-18 10:24:36,534 ] root - INFO - Creating dummy variables for categorical features
[ 2026-01-18 10:24:36,651 ] root - INFO - Renaming specific columns and casting to int
[ 2026-01-18 10:24:36,672 ] root - INFO - Mapping 'Gender' column to binary values
[ 2026-01-18 10:24:36,686 ] root - INFO - Dropping 'id' column
[ 2026-01-18 10:24:36,701 ] root - INFO - Creating dummy variables for categorical features
[ 2026-01-18 10:24:36,737 ] root - INFO - Renaming specific columns and casting to int
[ 2026-01-18 10:24:36,745 ] root - INFO - Custom transformations applied to train and test data
[ 2026-01-18 10:24:36,747 ] root - INFO - Starting data transformation
[ 2026-01-18 10:24:36,748 ] root - INFO - Entered get_data_transformer_object method of DataTransformation class
[ 2026-01-18 10:24:36,749 ] root - INFO - Transformers Initialized: StandardScaler-MinMaxScaler
[ 2026-01-18 10:24:36,750 ] root - INFO - Cols loaded from schema.
[ 2026-01-18 10:24:36,750 ] root - INFO - Final Pipeline Ready!!
[ 2026-01-18 10:24:36,751 ] root - INFO - Exited get_data_transformer_object method of DataTransformation class
[ 2026-01-18 10:24:36,751 ] root - INFO - Got the preprocessor object
[ 2026-01-18 10:24:36,752 ] root - INFO - Initializing transformation for Training-data
[ 2026-01-18 10:24:36,830 ] root - INFO - Initializing transformation for Testing-data
[ 2026-01-18 10:24:36,857 ] root - INFO - Transformation done end to end to train-test df.
[ 2026-01-18 10:24:36,858 ] root - INFO - Applying SMOTEENN for handling imbalanced dataset.
[ 2026-01-18 10:28:12,214 ] root - INFO - SMOTEENN applied to train-test df.
[ 2026-01-18 10:28:12,337 ] root - INFO - feature-target concatenation done for train-test df.
[ 2026-01-18 10:28:12,339 ] root - INFO - Entered the save_object method of utils
[ 2026-01-18 10:28:12,348 ] root - INFO - Exited the save_object method of utils
[ 2026-01-18 10:28:12,536 ] root - INFO - Saving transformation object and transformed files.
[ 2026-01-18 10:28:12,538 ] root - INFO - Data transformation completed successfully

In [18]:
model_trainer_artifact = pipline.start_model_trainer(data_transformation_artifact=data_transformation_artifact)

[ 2026-01-18 10:28:24,109 ] root - INFO - Entered initiate_model_trainer method of ModelTrainer class
[ 2026-01-18 10:28:24,225 ] root - INFO - train-test data loaded
[ 2026-01-18 10:28:24,226 ] root - INFO - Training RandomForestClassifier with specified parameters
[ 2026-01-18 10:28:24,227 ] root - INFO - train-test split done.
[ 2026-01-18 10:28:24,228 ] root - INFO - Model training going on...

------------------------------------------------------------------------------------------------
Starting Model Trainer Component

[ 2026-01-18 10:28:39,682 ] root - INFO - Model training done.
[ 2026-01-18 10:28:40,042 ] root - INFO - Model object and artifact loaded.
[ 2026-01-18 10:28:40,083 ] root - INFO - Preprocessing obj loaded.
[ 2026-01-18 10:28:40,814 ] root - INFO - Saving new model as performace is better than previous one.
[ 2026-01-18 10:28:40,815 ] root - INFO - Entered the save_object method of utils
[ 2026-01-18 10:28:40,826 ] root - INFO - Exited the save_object method of utils
[ 2026-01-18 10:28:40,827 ] root - INFO - Saved final model object that includes both preprocessing and the trained model
[ 2026-01-18 10:28:40,827 ] root - INFO - Model trainer artifact: ModelTrainerArtifact(trained_model_file_path='artifact\\01_18_2026_10_09_58\\model_trainer\\trained_model\\model.pkl', metric_artifact=ClassificationMetricArtifact(f1_score=0.9196257116296743, precision_score=0.8672570902016996, recall_score=0.9787252480610078, accuracy_score=0.9098440823999969))

In [19]:
model_evaluation_artifact = pipline.start_model_evaluation(data_ingestion_artifact=data_ingestion_artifact,
                                                                    model_trainer_artifact=model_trainer_artifact)

[ 2026-01-18 10:28:54,175 ] root - INFO - Initialized Model Evaluation Component.

------------------------------------------------------------------------------------------------

[ 2026-01-18 10:28:54,468 ] root - INFO - Test data loaded and now transforming it for prediction...
[ 2026-01-18 10:28:54,469 ] root - INFO - Mapping 'Gender' column to binary values
[ 2026-01-18 10:28:54,479 ] root - INFO - Dropping 'id' column
[ 2026-01-18 10:28:54,493 ] root - INFO - Creating dummy variables for categorical features
[ 2026-01-18 10:28:54,530 ] root - INFO - Renaming specific columns and casting to int
[ 2026-01-18 10:28:54,578 ] root - INFO - Trained model loaded/exists.
[ 2026-01-18 10:28:54,579 ] root - INFO - F1_Score for this model: 0.9196257116296743
[ 2026-01-18 10:28:54,580 ] root - INFO - Entered the get_bucket method of SimpleStorageService class
[ 2026-01-18 10:28:54,582 ] root - INFO - Exited the get_bucket method of SimpleStorageService class
[ 2026-01-18 10:28:56,045 ] root - INFO - Result: EvaluateModelResponse(trained_model_f1_score=0.9196257116296743, best_model_f1_score=None, is_model_accepted=True, difference=0.9196257116296743)
[ 2026-01-18 10:28:56,052 ] root - INFO - Model evaluation artifact: ModelEvaluationArtifact(is_model_accepted=True, changed_accuracy=0.9196257116296743, s3_model_path='model.pkl', trained_model_path='artifact\\01_18_2026_10_09_58\\model_trainer\\trained_model\\model.pkl')

In [17]:
if model_evaluation_artifact.is_model_accepted:
            model_pusher_artifact = pipline.start_model_pusher(model_evaluation_artifact=model_evaluation_artifact)

[ 2026-01-17 18:51:05,590 ] root - INFO - Entered initiate_model_pusher method of ModelTrainer class
[ 2026-01-17 18:51:05,591 ] root - INFO - Uploading artifacts folder to s3 bucket
[ 2026-01-17 18:51:05,591 ] root - INFO - Uploading new model to S3 bucket....
[ 2026-01-17 18:51:05,592 ] root - INFO - Entered the upload_file method of SimpleStorageService class
[ 2026-01-17 18:51:05,592 ] root - INFO - Uploading artifact\01_17_2026_18_13_41\model_trainer\trained_model\model.pkl to model.pkl in myproj-ani

------------------------------------------------------------------------------------------------

[ 2026-01-17 18:51:10,889 ] root - INFO - Uploaded artifact\01_17_2026_18_13_41\model_trainer\trained_model\model.pkl to model.pkl in myproj-ani
[ 2026-01-17 18:51:10,890 ] root - INFO - Exited the upload_file method of SimpleStorageService class
[ 2026-01-17 18:51:10,891 ] root - INFO - Uploaded artifacts folder to s3 bucket
[ 2026-01-17 18:51:10,891 ] root - INFO - Model pusher artifact: [ModelPusherArtifact(bucket_name='myproj-ani', s3_model_path='model.pkl')]
[ 2026-01-17 18:51:10,892 ] root - INFO - Exited initiate_model_pusher method of ModelTrainer class

In [1]:
from src.cloud_storage.aws_storage import SimpleStorageService
from src.exception import MyException
from src.entity.estimator import MyModel
import sys
from pandas import DataFrame

In [2]:
s3 = SimpleStorageService()

In [5]:
M = ModelEvaluationConfig()

In [6]:
Model = s3.load_model( M.s3_model_key_path,M.bucket_name)

[ 2026-01-19 14:26:26,031 ] root - INFO - Entered the get_file_object method of SimpleStorageService class
[ 2026-01-19 14:26:26,032 ] root - INFO - Entered the get_bucket method of SimpleStorageService class
[ 2026-01-19 14:26:26,035 ] root - INFO - Exited the get_bucket method of SimpleStorageService class
[ 2026-01-19 14:26:27,367 ] root - INFO - Exited the get_file_object method of SimpleStorageService class
[ 2026-01-19 14:26:28,595 ] root - INFO - Production model loaded from S3 bucket.

In [68]:
s3.s3_key_path_available(M.bucket_name, M.s3_model_key_path)

AttributeError: 'MyModel' object has no attribute 'bucket_name'

In [69]:
M= s3.load_model( M.s3_model_key_path,M.bucket_name)

AttributeError: 'MyModel' object has no attribute 's3_model_key_path'

In [60]:
!pip install scikit‑learn==1.8.0

ERROR: Invalid requirement: 'scikit‑learn==1.8.0': Expected end or semicolon (after name and no valid version specifier)
    scikit‑learn==1.8.0
          ^

In [7]:
import pandas as pd

In [8]:
df = pd.read_csv(r'C:\Users\Anindya.Sarkar\Documents\Vehilce-insurance\artifact\01_18_2026_13_06_58\data_ingestion\ingested\test.csv')

In [25]:
df.head()

,_id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,69454f04ca1cb71b0f23b075,Male,55,1,41.0,0,1-2 Year,Yes,2630.0,26.0,248,1
1,69454f04ca1cb71b0f227ef6,Female,54,1,28.0,0,1-2 Year,Yes,59219.0,26.0,244,0
2,694a80696035dec3034e5528,Female,32,1,33.0,1,< 1 Year,No,29412.0,152.0,242,0
3,694a806a6035dec303531306,Male,54,1,27.0,0,1-2 Year,Yes,30775.0,26.0,175,1
4,694a806a6035dec303509575,Female,58,1,28.0,0,1-2 Year,Yes,60958.0,26.0,270,1

In [9]:
df['Gender'] = df['Gender'].map({'Female': 0, 'Male': 1}).astype(int)

In [10]:
df = df.drop("_id", axis=1)

In [11]:
df = pd.get_dummies(df, drop_first=True)

In [12]:
df = df.rename(columns={
            "Vehicle_Age_< 1 Year": "Vehicle_Age_lt_1_Year",
            "Vehicle_Age_> 2 Years": "Vehicle_Age_gt_2_Years"
        })
for col in ["Vehicle_Age_lt_1_Year", "Vehicle_Age_gt_2_Years", "Vehicle_Damage_Yes"]:
            if col in df.columns:
                df[col] = df[col].astype('int')

In [13]:
from src.utils.main_utils import load_object

In [14]:
p =  load_object(r'C:\Users\Anindya.Sarkar\Documents\Vehilce-insurance\artifact\01_18_2026_13_06_58\data_transformation\transformed_object\preprocessing.pkl')

In [15]:
x, y = df.drop('Response', axis=1), df['Response']

In [16]:
x_hat = p.transform(x)

In [18]:
y_hat = Model.predict(x)

[ 2026-01-19 14:27:43,824 ] root - INFO - Starting prediction process.
[ 2026-01-19 14:27:43,859 ] root - INFO - Using the trained model to get predictions

In [19]:
from sklearn.metrics import f1_score,accuracy_score

In [21]:
f1_score(y,y_hat)

0.4236925395629239

In [51]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.compose import ColumnTransformer

In [53]:
from src.utils.main_utils import save_object, save_numpy_array_data, read_yaml_file
from src.constants import TARGET_COLUMN, SCHEMA_FILE_PATH, CURRENT_YEAR

In [54]:
schema_config = read_yaml_file(file_path=SCHEMA_FILE_PATH)

In [55]:
num_features = schema_config['num_features']
mm_columns = schema_config['mm_columns']
numeric_transformer = StandardScaler()
min_max_scaler = MinMaxScaler()

            # Creating preprocessor pipeline
preprocessor = ColumnTransformer(
                transformers=[
                    ("StandardScaler", numeric_transformer, num_features),
                    ("MinMaxScaler", min_max_scaler, mm_columns)
                ],
                remainder='passthrough'  # Leaves other columns as they are
            )

            # Wrapping everything in a single pipeline
final_pipeline = Pipeline(steps=[("Preprocessor", preprocessor)])

In [57]:
x

,Gender,Age,Driving_License,Region_Code,Previously_Insured,Annual_Premium,Policy_Sales_Channel,Vintage,Vehicle_Age_lt_1_Year,Vehicle_Age_gt_2_Years,Vehicle_Damage_Yes
0,1,55,1,41.0,0,2630.0,26.0,248,0,0,1
1,0,54,1,28.0,0,59219.0,26.0,244,0,0,1
2,0,32,1,33.0,1,29412.0,152.0,242,1,0,0
3,1,54,1,27.0,0,30775.0,26.0,175,0,0,1
4,0,58,1,28.0,0,60958.0,26.0,270,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...
190550,1,21,1,50.0,0,31952.0,160.0,87,1,0,1
190551,0,55,1,28.0,0,29395.0,124.0,295,0,0,1
190552,1,70,1,48.0,1,2630.0,15.0,20,0,0,0
190553,0,25,1,41.0,1,39450.0,152.0,13,1,0,0
190554,0,53,1,8.0,1,39815.0,124.0,55,0,0,0